Fix rational-compile for issue #153
SystemCrafters/crafted-emacs pull request #190
Opened 2022-07-09 13:19 UTC by abarocio80

# Fix `rational-compile` for issue #153 
Still have a strange bug with `native-compile`.

If you start your emacs session configured with `rational-compile` to
compile modules, init or config on startup, it will stall on a second
startup, complaining that `rational-package-install-package` is not
available.

The issue seems to be solved once you delete all `.elc` files from
`user-emacs-directory` and `rational-config-path`, and only then
`rational-compile-init`, `rational-compile-config` or
`rational-compile-modules`.

I don't know if that problem is specific to my system/configuration,
but I have tried daviwil's configuration with only `rational-compile`
added to it, and it crashes.

Maybe if `rational-package-install-package` is turned into a module,
and that module is required on each module that uses it, it could stop
complaining that it is not available.

Please read, comment, make suggestions and corrections.

2022-07-09 14:56 UTC, abarocio80 commented
Just seen issue #187. Will wait if it needs to first go through renaming process.

2022-07-09 16:56 UTC, ajxn commented
Is it possible to detect the absence of **rational-package-install-package** and then remove the .elc files as a hack, because it seams like this problem is also in my setup.

I am using latest master.

2022-07-13 19:05 UTC, abarocio80 commented
My guess is that, as those files got compiled withouth a `rational-package-install-package` function (in the compilation context), don't know what to do when the compiled file is loaded and executed, no matter if the function is already in the execution context.

So, I would propose that each module that make use of `rational-package-install-package` require the package `rational-package` (from #191, now renamed to `crafted-package` and the function `crafted-package-install-package` according to #194).

If some one knows better than this, pelase let me know.

2022-08-09 15:18 UTC, jeffbowman commented
@abarocio80 Do you want to take a look into the conflicts with this PR? Maybe once those are resolved we can merge it?

2022-08-09 15:57 UTC, abarocio80 commented
@jeffbowman, I think I did it.

2022-08-09 16:51 UTC, jeffbowman requested changes
Thanks, minor change requested.

2022-08-09 16:51 UTC, jeffbowman commented on modules/crafted-compile.el
> +  ""
Maybe remove the empty string, or (better) provide some doc here

2022-08-09 17:29 UTC, abarocio80 commented
OK. I think it is done.

2022-08-09 18:11 UTC, merged

2022-08-09 18:11 UTC, jeffbowman commented
Thanks!