Improve documentation to bootstrap straight package manager
SystemCrafters/crafted-emacs pull request #323
Opened 2023-08-08 20:14 UTC by monora

fixes #315

2023-08-09 01:44 UTC, jeffbowman commented
The info file needs to be regenerated.  

The `crafted-init-config` module sets the `crafted-emacs-home` variable, it does so by deducing the path where the `crafted-emacs` project code lives, as long as the value hasn't already been set.  So, it is safe to set in the `early-init.el` file, but I wonder if we might want to use a similar method. 

I'm not sold on copying the example to the `custom-modules` path and then loading it from there when it could easily be the user's `early-init.el` file by itself.  Doing so would mean the `crafted-emacs-home` value doesn't need to be set there, so less confusion on when/where/how to set that variable.  Additionally, if the `straight.el` maintainer devises a new method to bootstrap `straight`, then the example becomes a source of bugs, whereas depending on the user to own their own configuration means we don't need to track that process.  Technically, it is just **an example**, but in the face of such a change, someone will file a bug report that the example is wrong.  

On the other side of that coin, having a working example like this would be valuable and helpful to many, and the risk of changes isn't actually that high... sooo... I'm mostly in favor of merging this PR, but perhaps @jvdydev will share some thoughts as well.

2023-08-09 02:41 UTC, jvdydev commented
I think the idea of providing an example file for straight.el is generally a good idea (long-term I want to expand the examples section, but that should do for now).
Updating a broken example because of bootstrapping changes feels much less overhead than a module (maybe with a nice reminder that we don't officially support other package managers).

I agree on the copying an example and using it as a module (being equally not sold on it).
I think of the examples as a "copy in as my early-init/init and play around/get started"-type deal compared to the modules which are configuration blocks that are essential to the day-to-day usage.

I think personally, the only change on the docs should be maybe adding how to load the `crafted-package-config` (potentially setting `crafted-emacs-home` in the process, I'm open for either way on that one).
Otherwise the docs section above the "Here is an example using straight.el" is quite verbose on where those variables come from (in my opinion).

2023-08-09 02:46 UTC, jvdydev reviewed
Basically what my previous comment said, just with local comments, see above for some of the reasoning.

2023-08-09 02:46 UTC, jvdydev commented on docs/crafted-emacs.org
>    #+begin_src emacs-lisp
Maybe adding how to load `crafted-package-config` here would be nice

2023-08-09 02:46 UTC, jvdydev commented on docs/crafted-emacs.org
> +  You can find an example to bootstrap straight in the examples directory:
I'd personally keep the "You can find an example" part, but remove the copying to custom-modules block.

2023-08-09 02:46 UTC, jvdydev commented on examples/crafted-early-init-straight.el
> +;; Copy it to your custom-modules folder and load it in early-init.el like this:
Same here on the copying to custom-modules

2023-08-09 12:55 UTC, monora commented
With 267b5c4 I hope I resolved all comments. I reworded the doc again a little. Please have a look.

2023-08-09 15:25 UTC, jeffbowman requested changes
A few more changes.  This is good work and I really appreciate the effort you are putting into it.  Thanks for being willing to work with us on this PR! 

cc: @jvdydev

2023-08-09 15:25 UTC, jeffbowman commented on docs/crafted-emacs.org
> +    (find-file "../examples/crafted-early-init-straight.el")
```suggestion
    [[file:../examples/crafted-early-init-straight.el][crafted-early-init-straight.el]]
```

This should be a link as this document could be viewed online or in info.  (and therefore don't need the src block tags either. )

2023-08-09 15:25 UTC, jeffbowman commented on docs/crafted-emacs.org
> +  Assuming you copied it to your ~custom-modules~ folder, you can load it in
I might consider this an alternate approach.  The example file could be copied (or merged) with/as the user's `early-init.el` file

2023-08-09 15:26 UTC, jeffbowman commented
> Do you squash, when you merge?

I usually just rebase, but you are welcome to squash if you wish.

2023-08-10 07:38 UTC, monora commented on docs/crafted-emacs.org
> +  (load (expand-file-name "modules/crafted-package-config" crafted-emacs-home))
Done with fa8e2aed

2023-08-10 07:40 UTC, monora commented
> > Do you squash, when you merge?
> 
> I usually just rebase, but you are welcome to squash if you wish.

OK, than I would squash manually, so that you can merge if you are satisfied with my last changes.

2023-08-10 14:48 UTC, jeffbowman approved these changes

2023-08-10 22:22 UTC, monora commented
Squashed to one commit. Ready to merge.

2023-08-11 02:16 UTC, merged